---
title: "Lab3A_ManyaVivek"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
download.file(url = "https://ndownloader.figshare.com/files/2292169",
              destfile = "data_raw/portal_data_joined.csv")
```

```{r}
surveys <- read.csv("data_raw/portal_data_joined.csv")
```


```{r}
head(surveys)
```

# Challenge
```{r}
str(surveys)
```

# Number of rows and columns 
```{r}
dim(surveys)
```

# First 6 rows
```{r}
head(surveys)
```

# Last 6 rows 
```{r}
tail(surveys)
```

# Column names 
```{r}
names(surveys)
```

# summary statistics of each column 
```{r}
summary(surveys)
```

# first element in the first column of the data frame (as a vector)
```{r}
surveys[1,1]
```

# first element in the sixth column (as a vector)
```{r}
surveys[1,6]
```

# equivalent to head surveys 
```{r}
surveys[1:6, ]
```

# CHALLANGE 
1. Row 200 only
```{r}
surveys[200, ]
```
2. Extract last row
```{r}
n_row <- nrow(surveys)
```
```{r}
surveys[n_row, ]
```
3. Extract middle row
```{r}
surveys[n_row/2, ]
```
4. 
```{r}
surveys[-(7:n_row), ]
```


## FACTORS

```{r}
plot(as.factor(surveys$sex))
```

```{r}
sex <- factor(surveys$sex)
head(sex)
```

```{r}
levels(sex)
```

```{r}
levels(sex)[1] <- "undetermined"
levels(sex) 
```

```{r}
head(sex)
```

# Challange 
```{r}
levels(sex)[2:3] <- c("female", "male")
sex <- factor(sex, levels = c("female", "male", "undetermined"))
plot(sex)
```

# Challange 
1. 
```{r}
animal_data <- data.frame(
          animal = c( "dog", "cat", "sea cucumber", "sea urchin"),
          feel = c( "furry", "squishy","leathery", "spiny"),
          weight = c(45, 8, 1.1, 0.8)
          )
```

2. 
```{r}
country_climate <- data.frame(
       country = c("Canada", "Panama", "South Africa", "Australia"),
       climate = c("cold", "hot", "temperate", "hot/temperate"),
       temperature = c(10, 30, 18, 15),
       northern_hemisphere = c("TRUE", "TRUE", "FALSE", "FALSE"),
       has_kangaroo = c(5, 10, 15, 1)
       )
```

