---
title: "Lab4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
report_03_11_2020 <- 
read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv")) %>% 
  rename(Country_Region = "Country/Region", Province_State = "Province/State")
```

```{r}
str(report_03_11_2020)
```

```{r}
head(report_03_11_2020)
```

```{r}
library(DT)
datatable(report_03_11_2020)
```

### Exercises (Part 1)

# 1. 

```{r}
report_03_13_2020 <-
read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>% 
  rename(Country_Region = "Country/Region", Province_State = "Province/State")
```

```{r}
str(report_03_13_2020)
```


```{r}
report_09_13_2020 <-
read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv"))  
```

```{r}
str(report_09_13_2020)
```

# 2. 
```{r}
report_03_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarise(totaldeaths = sum(Deaths))
```

```{r}
report_09_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarise(totaldeaths = sum(Deaths))
```

# 3.CONFIRMED CASES PER U.S STATE USE

### 03/13/2020
```{r}
filter(report_03_13_2020, Country_Region == "US") %>% 
  group_by(Province_State) %>% 
  summarise(totalconfirmed = sum(Confirmed))
```

### 09/13/2020
```{r}
filter(report_09_13_2020, Country_Region == "US") %>% 
group_by(Province_State) %>% 
summarise(totalconfirmed = sum(Confirmed))
```



# 4. TOP 10 COUNTRIES OF DEATH

### 03/13/2020
```{r}
report_03_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarise(totaldeaths = sum(Deaths)) %>% 
  arrange(desc(totaldeaths)) %>% 
  slice(1:10)
```

### 09/13/2020
```{r}
report_09_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarise(totaldeaths = sum(Deaths)) %>% 
  arrange(desc(totaldeaths)) %>% 
  slice(1:10)
```


# ----------------------------------------------------------------------------

```{r}
install.packages("tidyverse")
```

```{r}
library(tidyverse)
```


# Exercise 2 

## 5

### Graph: 10 countries with the confirmed cases and deaths on 03/13/2020
```{r}
report_03_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed), Deaths = sum(Deaths), min_deaths = min(Deaths)) %>% 
arrange(desc(min_deaths)) %>% 
slice(1:10)

ggplot(data = report_03_13_2020, mapping = aes(x = Country_Region, y = Deaths)) +
    geom_boxplot()
```


# Graph: 10 countries with the confirmed cases and deaths on 09/13/2020
```{r}
report_09_13_2020 %>% 
  group_by(Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed), Deaths = sum(Deaths), min_deaths = min(Deaths)) %>% 
arrange(desc(min_deaths)) %>% 
slice(1:10)

ggplot(data = report_09_13_2020, mapping = aes(x = Country_Region, y = Deaths)) +
    geom_boxplot()
```
## 6

# Graph 1: 10 states with the most confirmed cases and deaths on 3/12/2020 


```{r}
report_03_13_2020 %>% 
  group_by(Province_State) %>% 
  summarise(Confirmed = sum(Confirmed), Deaths = sum(Deaths), min_deaths = min(Deaths)) %>% 
arrange(desc(min_deaths)) %>% 
slice(1:10)

ggplot(data = report_03_13_2020, mapping = aes(x = Province_State, y = Deaths)) +
    geom_boxplot()
```

```{r}
report_09_13_2020 %>% 
  group_by(Province_State) %>% 
  summarise(Confirmed = sum(Confirmed), Deaths = sum(Deaths), min_deaths = min(Deaths)) %>% 
arrange(desc(min_deaths)) %>% 
slice(1:10)

ggplot(data = report_09_13_2020, mapping = aes(x = Province_State, y = Deaths)) +
    geom_boxplot()
```