---
title: "Lab9x"
author: "Manya Vivek"
date: "10/28/2020"
output: html_document
---



```{r}
library(stringr)
library(tidyverse)
```


```{r, eval= FALSE}
if(<condition>) {
        ## do something
} 
## Continue with rest of code
```

```{r, eval = FALSE}
if(<condition>) {
        ## do something
} 
else {
        ## do something else
}
```
```{r}
x <- runif(1, 0, 10)  
if(x > 3) {
        y <- 10
} else {
        y <- 0
}
```

```{r}
for(i in 1:10) {
        print(i)
}
```

```{r}
x <- c("ape", "bat", "cat", "dog")
for(i in 1:4) {
        ## Print out each element of 'x'
        print(x[i])  
}
```

```{r}
## Generate a sequence based on length of 'x'
for(i in seq_along(x)) {   
        print(x[i])
}
```

```{r}
for(letter in x) {
        print(letter)
}
```

```{r}
for(i in 1:4) print(x[i])
```

```{r}
x <- matrix(1:6, 2, 3)
for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
                print(x[i, j])
        }   
}
```
# while Loops
```{r}
count <- 0
while(count < 10) {
        print(count)
        count <- count + 1
}
```

```{r}
z <- 5
set.seed(1)
while(z >= 3 && z <= 10) {
        coin <- rbinom(1, 1, 0.5)
        
        if(coin == 1) {  ## random walk
                z <- z + 1
        } else {
                z <- z - 1
        } 
}
print(z)
```

# FUNCTIONS
```{r}
f <- function(num = 1) {
        hello <- "Hello, world!\n"
        for(i in seq_len(num)) {
               cat(hello)
        }
        chars <- nchar(hello) * num
         chars
 }
 f(3)   
```

```{r}
f <- function(num = 1) {
  hello <- "Hello Underworld!!"
  for(i in seq_len(num)) {
    cat(hello)
  }
  chars <- nchar(hello) * num
         chars
}
f()
f(5)
```

